//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class normCinemaEntities : DbContext
    {
        public normCinemaEntities()
            : base("name=normCinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<film> film { get; set; }
        public virtual DbSet<film_type> film_type { get; set; }
        public virtual DbSet<margin> margin { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<room_type> room_type { get; set; }
        public virtual DbSet<session> session { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
    }
}
