//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int nomber_row { get; set; }
        public int nomber_seat { get; set; }
        public int id_ticket { get; set; }
        public int id_margin { get; set; }
        public int id_session { get; set; }
    
        public virtual margin margin { get; set; }
        public virtual session session { get; set; }
    }
}
